### PR TITLE
[FIX][10.0] Fixes #159 - improves new disease view

### LINKED ISSUE #159: New disease form looks squashed
create-disease

### PR DESCRIPTION
**Pull request by kellylougheed**
- Improves the view for creating or editing a disease by reducing the number of groups
- Includes fix from #158 

Before:
before

After:
after

### CODE REVIEW

**Review by woodbrettm — CHANGES_REQUESTED** [review]
Nice! Was able to create a disease locally.

Just a Couple things:
* I noticed with some of the fields, the second and third words are not capitalized (e.g. Date start treatment.). I must have forgotten to add `string=` attributes to those when migrating modules.
* test_action_invalidate in medical_patient_disease.tests.test_medical_patient is failing for me locally, not sure if the same for you though. Logs are saying that no super method exists when [this line is run](https://github.com/LasLabs/vertical-medical/blob/release/10.0/medical_patient_disease/models/medical_patient.py#L29). Perhaps @LasLabs/admins can chime in as to whether we should remove that line or add a super method to medical patient somewhere.

**Comment by kellylougheed** [comment]
Thanks for the feedback @bmw95! I added some string attributes for more consistent capitalization. I'm not getting any errors from testing on local, but I'm happy to make any changes for the nonexistent super method.

**Comment by lasley** [comment]
Regarding the string attributes, I agree it looks like shit, but we should leave it. Don't change back or anything, but don't worry for future.

Odoo 11 will be title casing and automatically removing `_id` and `_ids` - https://github.com/odoo/odoo/blob/master/odoo/fields.py#L456

**Review by woodbrettm — APPROVED** [review]

**Review by tedsalmon — APPROVED** [review]
LGTM! 👍

**Pull request merged**
