### PR TITLE
[9.0][IMP] medical prescription state

### PR DESCRIPTION
**Pull request by lasley**
This is dependent on
- [x] #6

This PR implements the abstract state logic instead of built in

It also adds stages on prescription lines

### CODE REVIEW

**Comment by lasley** [comment]
Rebased

**Comment by tedsalmon** [comment]
Hey @lasley,

Your lint and tests are failing so I can't approve this :(

**Comment by lasley** [comment]
@t3ddftw Lint fixed and incompatible, now deprecated module removed.

**Review by tedsalmon — APPROVED** [review]
I'm not sure where the drop in test coverage is coming from as this didn't have proper tests to begin with. Either way, 👍

**Comment by lasley** [comment]
Coveralls sucking at change detection basically

**Pull request merged**
