### PR TITLE
[FIX] medical_prescription_sale_stock_us: Fix type strict evals

### PR DESCRIPTION
**Pull request by lasley**
- Change type strict evals for lazy False

### CODE REVIEW

**Comment by lasley** [comment]
@obulkin - This was your code, so take note of this. Type strict eval is bad unless you have a good reason.

**Comment by obulkin** [comment]
@lasley - I think I just wanted to avoid the specific edge case where `refill_threshold` is `False`, which seemed like it would break the code. However, it looks like `False * float` safely evaluates to `0`, so that whole line of reasoning is mistaken.

Now that I'm looking at the code again, it looks inconsistent with the description for `refill_threshold` provided here: https://github.com/laslabs/vertical-medical/blob/release/9.0/medical_prescription_sale_stock_us/models/res_company.py#L15. If the threshold is the proportion that must be used, then we should disallow refills when the amount remaining exceeds `(1 - refill_threshold) * rec_id.qty`. As it stands, we're treating the threshold as if it were the maximum proportion that can be remaining when a refill is dispensed, so either the logic or the help text needs to get updated.

For future reference, why is a type-strict eval a bad practice?

**Comment by tedsalmon** [comment]
> For future reference, why is a type-strict eval a bad practice?

Because non-type strict evals will account for all plausible "False" values of any type. For example, take the following code into consideration:

```
>>> zero = 0
>>> if zero is False:
...  print 'This line will not print'
... 
>>> 
>>> if not zero:
...  print 'This line will print'
... 
This line will print
>>> 
>>> empty_string = ''
>>> 
>>> if empty_string is False:
...  print 'This line will not print'
... 
```

@lasley is better at explaining these sorts of things but I thought I'd chime in :)

**Comment by obulkin** [comment]
@t3ddftw - That makes sense. In this particular case, the only possible falsy values seem to be `0.0` and `False`, and at the time it seemed better to only filter out `False`, so I was intentionally making the comparison more specific. In retrospect, that was unnecessary.

**Review by tedsalmon — APPROVED** [review]
👍  Changes LGTM :)

**Comment by lasley** [comment]
My explanation is that you should generally always be lazy when possible, unless you have an explicit reason for not doing so.

**Comment by lasley** [comment]
Also I'm not sure if I understand your edge case. Can you provide an example case elaborating the scenario?

**Comment by obulkin** [comment]
@lasley - I'm assuming you're referring to the second part of my comment. If so, it wasn't really an edge case. The logic in the code is just inconsistent with the help text for the `refill_threshold` field. 

The text says that the threshold is the amount of fill that must be used before allowing a refill. This means that if the threshold is 0.75, 75% of a fill must be used up before a refill can happen, which in turn means the unused portion can at most be 25%. It follows that a refill should not be allowed if `pending_and_unused > (1 - refill_threshold) * rec_id.qty`, but the current logic checks for `pending_and_unused > refill_threshold * rec_id.qty`. This is equivalent to treating the threshold as if it were the maximum amount of unused fill that can be present when allowing a refill. Consequently, either the logic or the help text needs to change.

**Pull request merged**
