### PR TITLE
[10.0][FIX] website patient form delete button

### PR DESCRIPTION
**Pull request by woodbrettm**
#### This pull request addresses the following:
* Add deactivated filter to abstract medical entity tree views
* Fix permission issue with medical patient diseases
* Add confirmation prompt when users click on delete button on forms

#### Question
I added medical_patient_disease as a dependency to website_portal_medical_patient. Is that ok? Perhaps we should have a website_portal_medical_patient_disease module or something so that a website module can be directly mapped to the backend disease module.

The issue is associated with adding portal access to medical.patient.disease

### CODE REVIEW

**Comment by woodbrettm** [comment]
Tests are failing from medical_patient_disease. Will leave for now.

**Comment by lasley** [comment]
I'm good with the dependency. We can think about breaking it up later if we find a use case.

Weird that tests are failing... why is that not the case on [release/10.0](https://travis-ci.org/LasLabs/vertical-medical/builds/264885263)? Did you base from that?

**Comment by woodbrettm** [comment]
Yup from release/10.0. I've noticed it fail on my local build in the past as well. Interesting that it's showing up now.

**Comment by lasley** [comment]
Rebased now that #238 is merged

**Comment by woodbrettm** [comment]
woot @lasley thanks for the fix. All checks passing now.

**Review by lasley — APPROVED** [review]

**Pull request merged**
