### PR TITLE
[9.0][MIG] Upgrade Medical Physician to 9.0

### PR DESCRIPTION
**Pull request by woodbrettm**
### Pre-Note
- Separated the migration into multiple commits so you can track what I changed vs what was migrated. 
### Commits
- ced2212 
  - Migration commit. Mostly involves stylistic changes to match conventions. Nothing major functionally.
- ebc1727 
  - Refactored the demo data and separated it into res partner physician ids and medical physician ids (similar to demo data in medical)
  - Refactored tests to use demo data
  - Added Kanban view to physician so it's more consistent with the presence of kanban for patient
  - Removed tree view option for `Physician [Self]` action, so it just goes straight to the form view for the current logged in user.
- 23563bc
  - **Important** Major functional changes in this commit
  - Removed `medical.physician.schedule.template` and the respective set unavailable wizard
  - Removed `medical.physician.service`
  - The reason I removed medical.physician.schedule.template and medical.physician.service was because:
    - the action_set_unavailable method in the wizard was calling methods of which I could not seem to find in both ours and OCA's repo.
    - Seems like the functionality has been replaced with or should belong in the medical.appointment module
  - Can hard reset this commit should need be ^^

**Cheers!**
Brett

### CODE REVIEW

**Comment by lasley** [comment]
Hmmm so I think we're going to need to do these a slightly different way - I'm having trouble determining what I did and what you did & I got a comment from OCA as well.

I'll fix this one, but for subsequent PRs when you do the initial migration commit can you just commit under my email instead? That way we can isolate the work that was done in the LasLabs branch from the work that is being done specifically for OCA migration.

**Comment by lasley** [comment]
This looks fine commit wise, I'll rebase the real PR on this and perform review there

**Comment by woodbrettm** [comment]
Ok sweet. Yeah I noticed that! Tried to separate things a little further here and was planning on making a separate migration commit in the future. Totally forgot I can commit under your name though that's super cool.

**Comment by woodbrettm** [comment]
[Queue evil laugh]

**Comment by lasley** [comment]
That's why I sign my commits- any non-signed commit was not created by me (or was edited by someone other than me), unless it's a merge because I'm too lazy to not do it in Github UI 😉 

image

**Pull request closed without merging**
