### PR TITLE
[10.0][IMP] medical_prescription_stage: Switch to new kanban module

### PR DESCRIPTION
**Pull request by lasley**
Forward port of #70 & #117

[IMP] medical_prescription_stage: Switch to new kanban module  …
* Switch from `medical_base_kanban` to `base_kanban_stage`
* Add requirements to oca_requirements.txt

[REM] medical_base_kanban: Deprecate module  …
* Deprecate medical_base_kanban in favor of OCA/server-tools/base_kanban_stage

### CODE REVIEW

**Review by tedsalmon — APPROVED** [review]
LGTM! 👍

**Comment by jcdrubay** [comment]
You are sooo fast! I believe that you are right and going in the right direction by re-using more of existing !

No code review here, but big THANKS for your great quality work and fast contributions!  :+1:

**Comment by jcdrubay** [comment]
A small note: this is waiting for https://github.com/OCA/server-tools/pull/681

**Comment by lasley** [comment]
> A small note: this is waiting for OCA/server-tools#681

Haha yeah we're backing up on dependencies quite nicely. The note is in our oca_dependencies though - also keep that in mind when you're installing incubator local. There's a website dependency in there that's not merged too.

https://github.com/LasLabs/vertical-medical/blob/release/10.0/oca_dependencies.txt#L4

**Pull request merged**
