### PR TITLE
[10.0][FIX] website_sale_medical_prescription: Upgrade API

### LINKED ISSUE #94: 500 error when checking out with "Prescription Step Option" selected
With website_sale_medical_prescription_us installed, I got this error while checking out: sale_get_order() got an unexpected keyword argument 'context'

### PR DESCRIPTION
**Pull request by lasley**
* Upgrade request.website API usage in controller to fix LasLabs#94

### CODE REVIEW

**Comment by lasley** [comment]
Re coverage drop: this module has no tests, so a bugfix isn't the place to start IMO.

The lack of tests does explain the bug though, so at least we can call it a win for TDD!

**Review by kellylougheed — COMMENTED** [review]
I don't get a 500 error when going to "Prescription Info," but checkout jumps right from "Shipping & Billing" to "Payment." Was that the intended result?

**Comment by lasley** [comment]
Sounds like you maybe have an OTC item in your cart. The one I use in demo that is Rx is Simvastatin

**Comment by kellylougheed** [comment]
Checked out with Simvastatin, but then I got a different 500 error: 'website' object has no attribute 'render'

**Comment by lasley** [comment]
Dammit that uncovers a whole other can of worms! Check out the My Medical (dropdown at top right, where you would normally log out)

Either way, fix submitted here & will hit up the others in another PR to reduce scope explosion.

**Comment by kellylougheed** [comment]
Yeah, I get the same error when I go there. I'll approve, though (since there was a fix)!

**Review by kellylougheed — APPROVED** [review]

**Comment by lasley** [comment]
Optimistic merge; incubator

**Pull request merged**
