### PR TITLE
[10.0][IMP] sale_medical_prescription: Forward Port

### PR DESCRIPTION
**Pull request by lasley**
Forward port of OCA#83

### CODE REVIEW

**Review by tedsalmon — COMMENTED** [review]
Tests are failing:

```
External ID not found in the system: sale_medical_prescription.medical_medication_patient_1_simv_1" while parsing /home/travis/build/LasLabs/vertical-medical/sale_medical_prescription/demo/medical_prescription_order_line_demo.xml:12
```

**Review by jcdrubay — COMMENTED** [review]
Bravo for adding so much demo data and unit tests. :+1: 

Overall screening makes me feel that the code is good. I guess I should test before approving this big PR.

I believe that we should add to the Roadmap:
 - Check if some fields/logic should be moved to `medical_prescription`
 - Improve module description in the readme.

**Comment by lasley** [comment]
@bmw95 - Please take a look at & fix the build fail. You did (and are doing) all the demo data, so I'm sure this is something you have or will run into on v9.

@jcdrubay - this is just a cross-port from a PR already approved in OCA, so probably not too much testing necessary until we take the leap back to OCA with the v10. I'd say assuming cursory looks good in terms of style & CI 🍏 , we're good to optimistic merge.

Notes added in Roadmap.

**Comment by woodbrettm** [comment]
@lasley looks like medical_prescription_order_line demo has not been updated, I'll take a look.

**Review by jcdrubay — APPROVED** [review]
:+1:

**Comment by woodbrettm** [comment]
Updated. Tests and runbot are failing from sale_stock_medical_prescription and sale_crm_medical_prescription.

**Comment by woodbrettm** [comment]
@LasLabs/admins this build is passing now. Made some adjustments to sale_stock_medical_prescription.

**Comment by lasley** [comment]
Woot thanks @bmw95! Can you please squash your commits into logical chunks please? I don't care about my own attribution, so don't worry about squashing mine into your's

**Comment by woodbrettm** [comment]
@lasley Squashed!

**Pull request merged**
