### PR TITLE
[10.0][FIX] medical: Fix partner patient smart button.

### PR DESCRIPTION
**Pull request by woodbrettm**

### CODE REVIEW

**Comment by woodbrettm** [comment]
@lasley I'm having some issues with the Runbot. It seems to be passing, but when clicking on details it's saying 404 not found.

**Comment by woodbrettm** [comment]
This is ready for review. Issue with the odoo/odoo runbot, some website errors that are unrelated here.

**Comment by woodbrettm** [comment]
@lasley thanks! Both travis builds are passing now.

**Review by lasley — APPROVED** [review]

**Comment by lasley** [comment]
THnask @bmw95

**Pull request merged**
