### PR TITLE
[10.0][FIX] medical: Patient form view

### LINKED ISSUE #89: Error when creating patient: Uncaught TypeError: Cannot read property 'string_true' of undefined

### PR DESCRIPTION
**Pull request by lasley**
* Fix archive button on patient form view to fix #89

### CODE REVIEW

**Comment by lasley** [comment]
Actually hold up, this active button doesn't even freaking work. Looks like the handler has been changed; WIP

**Comment by lasley** [comment]
Alright ready for review - the configurator section was duplicating active and causing funny results.

**Comment by jcdrubay** [comment]
LGTM

**Comment by lasley** [comment]
Merging on approval of OCA branch, which contained this commit

**Pull request merged**
