### PR TITLE
[MIG][10.0] medical_pathology_import

### PR DESCRIPTION
**Pull request by lasley**
* Rename manifest
* Change openerp references to odoo
* Bump version

Depends:
- [x] #54 
- [x] #49

### CODE REVIEW

**Comment by obulkin** [comment]
I've addressed the test failures and changed the module license to LGPL. The PR should be ready for review now.

**Comment by woodbrettm** [comment]
is #54 done? Not sure if that matters, just saw it in the top comment checklist.

**Comment by obulkin** [comment]
Good question. It was closed in favor of https://github.com/OCA/vertical-medical/pull/140, which is now closed as well. However, I'll be making some additional changes here based on the comments in https://github.com/OCA/vertical-medical/pull/140, so I'll make this a WIP again.

**Comment by obulkin** [comment]
I've made some more changes that factor in the comments in https://github.com/OCA/vertical-medical/pull/140, so the PR should be ready for review now.

**Review by lasley — COMMENTED** [review]
LGTM thanks Oleg. I'm going for an optimistic merge here, we can review more when it goes to OCA

**Pull request merged**
